#quick way to get the muon sim to run

/vis/scene/create
/vis/open OGLIX 800x800-0+0
/vis/verbose errors
/vis/viewer/set/style surface
/vis/viewer/set/autoRefresh false
/vis/viewer/set/upVector 1 0 0
/vis/viewer/set/viewpointVector 0 1 0

#/process/optical/scintillation/setFiniteRiseTime 1

/run/initialize
/vis/drawVolume
/vis/viewer/flush

/control/verbose 0 #2
/run/verbose 0 #2
/event/verbose 0 #0
/tracking/verbose 0 #1
/run/particle/verbose 0
/process/verbose 0

/vis/scene/endOfEventAction accumulate 1
/tracking/storeTrajectory 1
/vis/scene/add/trajectories

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron magenta
/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow
/vis/modeling/trajectories/drawByParticleID-0/set e- black
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton cyan
/vis/modeling/trajectories/drawByParticleID-0/set mu- red
/vis/modeling/trajectories/drawByParticleID-0/set proton orange
/vis/modeling/trajectories/drawByParticleID-0/set monopole blue
#/vis/modeling/trajectories/list
/vis/viewer/set/background white

#/gun/yvertex 300 cm
#/gun/xvertex 300 cm
#/gun/zvertex 50 cm
#/gun/particle monopole
/vis/viewer/flush
/run/beamOn 10
