#quick way to get the muon sim to run

#/process/em/fluo true
#/process/em/auger true
#/process/em/pixe true

/run/initialize

/gps/particle gamma
# center of slab
/gps/position -1300 0 -1250 mm

#Na22
#/gps/ene/type Mono
#/gps/ene/mono 500 keV

#Na22
#/gps/ene/type Mono
#/gps/ene/mono 511 keV

#Mn-54
#/gps/ene/type Mono
#/gps/ene/mono 835 keV

/gps/ene/type User
/gps/hist/type energy

#Unif
#/gps/hist/point 0 0
#/gps/hist/point 0.001 100
#/gps/hist/point 0.800 100
#/gps/hist/point 0.801 0

#Cd109
/gps/hist/point 0 0
/gps/hist/point 0.003075 0
/gps/hist/point 0.003080 9.35
/gps/hist/point 0.003085 0
/gps/hist/point 0.022095 0
/gps/hist/point 0.022100 85.23
/gps/hist/point 0.022105 0
/gps/hist/point 0.025015 0
/gps/hist/point 0.025020 16.86
/gps/hist/point 0.025025 0
/gps/hist/point 0.088035 0
/gps/hist/point 0.088040 3.61
/gps/hist/point 0.088045 0


#Ba133
#31 99
#356 62
#81 34
#303 18

#/gps/hist/point 0 0
#/gps/hist/point 0.031 0
#/gps/hist/point 0.0312 99
#/gps/hist/point 0.0315 0
#/gps/hist/point 0.081 0
#/gps/hist/point 0.0812 34
#/gps/hist/point 0.0815 0
#/gps/hist/point 0.303 0
#/gps/hist/point 0.3032 18
#/gps/hist/point 0.3035 0
#/gps/hist/point 0.356 0
#/gps/hist/point 0.3562 62
#/gps/hist/point 0.3565 0


#Co57
#122 86
#136 11
#14 9
#/gps/hist/point 0 0
#/gps/hist/point 0.014 0
#/gps/hist/point 0.0142 9
#/gps/hist/point 0.0145 0
#/gps/hist/point 0.122 0
#/gps/hist/point 0.1222 86
#/gps/hist/point 0.1225 0
#/gps/hist/point 0.136 0
#/gps/hist/point 0.1362 11
#/gps/hist/point 0.1365 0

#Am241
#59.5 36
#14 15
#18 9
#/gps/hist/point 0 0
#/gps/hist/point 0.0140 0
#/gps/hist/point 0.0142 15
#/gps/hist/point 0.0145 0
#/gps/hist/point 0.018 0
#/gps/hist/point 0.0182 9
#/gps/hist/point 0.0185 0
#/gps/hist/point 0.0595 0
#/gps/hist/point 0.0597 36
#/gps/hist/point 0.0600 0

#Eu 152
#121.7 28
#344.2 26
#1408  21
#964   14
#1112  13
#778.9   12
#1085.8  10

#/gps/hist/point 0 0
#/gps/hist/point 0.1215 0
#/gps/hist/point 0.1217 28
#/gps/hist/point 0.1220 0
#/gps/hist/point 0.3440 0
#/gps/hist/point 0.3442 26
#/gps/hist/point 0.3445 0
#/gps/hist/point 0.7787 0
#/gps/hist/point 0.7789 12
#/gps/hist/point 0.7792 0
#/gps/hist/point 0.9638 0
#/gps/hist/point 0.9640 14
#/gps/hist/point 0.9643 0
#/gps/hist/point 1.0856 0
#/gps/hist/point 1.0858 10
#/gps/hist/point 1.0861 0
#/gps/hist/point 1.1118 0
#/gps/hist/point 1.1120 13
#/gps/hist/point 1.1123 0
#/gps/hist/point 1.4078 0
#/gps/hist/point 1.4080 21
#/gps/hist/point 1.4083 0



#/gps/hist/point 0 8.83
##/gps/hist/point 0.0599 8.83
#/gps/hist/point 0.0601 0.5
#/gps/hist/point 0.995 0.5
#/gps/hist/point 1.00 0

/gps/ang/type iso
#/gps/direction -1 0 0
#/gps/number 10


#/run/fname /media/ryan/Storage/computing/beamRadSim/data/60keV1MeVMixed_mixedAbsAuAgScint_5stack/
#/run/fname /media/ryan/Storage/computing/beamRadSim/data/electron/
#/run/beamOn 1000000
/run/beamOn 10
